### ISSUE TITLE
Incompatibility with Server Translation API (and possibly other mods)

### ISSUE THREAD

**Issue by Patbox** [Draylar/maybe-data#5]
This mixin https://github.com/Draylar/maybe-data/blob/1.18.2/src/main/java/draylar/maybedata/mixin/ServerResourceManagerMixin.java
breaks with Server Translation API or any other mod mixing into the same place (which shouldn't be done). Ideally you should use fabric's resource loader api instead. 

It would be just:
```
ResourceLoader.get(ResourceType.SERVER_DATA).registerReloader(yourloader);
```

**Comment by Draylar** [comment]
Thanks for letting me know, fixed & pushing out updates to my projects that depend on it. For some reason I was always under the impression you could mutate return values without canceling future injects.. apparently not!😆
